repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: generate/ast.dump
      - id: end-of-file-fixer
        exclude: generate/ast.dump
      - id: check-yaml
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        exclude: api.go
      - id: go-imports
        exclude: api.go
      - id: golangci-lint
      - id: go-unit-tests
